"""empty message

Revision ID: 0eda6b718cec
Revises: 7aa9ebb79c54
Create Date: 2025-07-07 09:49:59.252519

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eda6b718cec'
down_revision = '7aa9ebb79c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('node_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('node_id',
               existing_type=sa.String(length=32),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###
