"""empty message

Revision ID: 7aa9ebb79c54
Revises: afb0189e4331
Create Date: 2025-07-07 09:31:00.875624

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa9ebb79c54'
down_revision = 'afb0189e4331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_id', models.types.StringUUID(), nullable=False))
        batch_op.create_unique_constraint('report_node_id_idx', ['node_id'])

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_column('sequence_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_number', sa.BIGINT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('report_node_id_idx', type_='unique')
        batch_op.drop_column('node_id')

    # ### end Alembic commands ###
